version: '3'
services:
    mongodb:
        image: "mongo:8.2"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        ports:
            - "27017:27017"
        volumes:
            - ./mongodb-data:/data/db  # MongoDB 데이터를 로컬 디렉터리에 저장
            - ./mongodb-data/var:/var/log/mongodb  # MongoDB 데이터를 로컬 디렉터리에 저장
            - ./mongod.conf:/etc/mongod.conf  # MongoDB 설정 파일을 로컬 디렉터리에 저장
        command: ["mongod", "--config", "/etc/mongod.conf"]  # 커스텀 설정 파일 사용



